language: php

php:
  - 5.5

install:
  composer install

before_script:
  - pear channel-discover pear.phpqatools.org
  - pear install -f --alldeps phpqatools/phpqatools
  - phpenv rehash
 
script:
 - ant build.travisci

after_script:
  - php vendor/bin/coveralls -v