language: php

php:
  - 5.5

install:
  composer install

before_script:
  - composer selfupdate
  - pear channel-discover pear.phpqatools.org
  - pear channel-discover pear.phpunit.de
  - pear channel-discover pear.symfony.com
  - pear channel-discover components.ez.no
  - pear install -f phpqatools/phpqatools
  - pear install --alldeps ezc/eZComponents
  - phpenv rehash

script:
  - ant build.travisci

after_script:
  - php vendor/bin/coveralls -v